name: E2E Tests

on: 
  workflow_dispatch: 

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7

        
      - name: Cypress run
        uses: cypress-io/github-action@v7
        with:
          start: npm start
          browser: chrome
      - name : Upload Cypress Screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-screenshots-chrome
          path: cypress/screenshots
